### ISSUE TITLE
background color for highlighted search matches a little too light

### ISSUE THREAD

**Issue by rcrooks** [IKKI2000/IKKI-VSCode-Dark-Theme#1]
Hi @IKKI2000 I love this theme! So soothing to the eyes.

There is one small issue -- when you search in file the highlght color for matches is so light that you can't read the actual text.
<img width="1001" alt="2020-07-28_14-16-50" src="https://user-images.githubusercontent.com/619617/88705411-7c4d1e00-d0dd-11ea-89b2-ae3bdab53a42.png">

**Comment by IKKI2000** [comment]
Hi @rcrooks thank you for your love of this theme and your 5-star rating.

Because the dark theme is adapted from the light theme, the release was in a hurry, so v0.1.0 has many imperfections, including the issue you mentioned.

Later updated versions 0.2.0 and 0.3.0 have been optimized and improved, but do not include editor colors, diff editor colors, editor widget colors, peek view colors, merge conflicts colors.

Because editor related colors is more complex, so I left it to the end to improve. I will release the final version 1.0.0 before August. I hope you will like it. Thank you again!

**Comment by rcrooks** [comment]
Hi @IKKI2000 very good. It's already a beautiful theme. I look forward to more fine-tuning.
